const app=document.getElementById('app'), back=document.getElementById('back');
const state=JSON.parse(localStorage.getItem('jlpt_state')||'{"done":{},"quiz":0,"correct":0}');
const save=()=>localStorage.setItem('jlpt_state',JSON.stringify(state));
const n5=["あいさつ・自己紹介","これ／それ／あれ","ここ・そこ・あそこ","時間・日付","場所と存在","家族・人の紹介","好き・嫌い","日常生活","移動と交通","買い物","食べ物・飲み物","形容詞","毎日の予定","て形の基礎","て形の依頼","許可・禁止","できます・能力","趣味と経験","普通形の基礎","比較","予定・つもり","理由と原因","て形の復習","会話練習","総復習"];
const n4=["もうすぐ／まだ","んです","てあげる・てもらう・てくれる","たら","なら","そうです","ようです","ために","のに","ところです","ばかりです","はずです","かもしれません","と思います","と言います","命令・禁止","間接疑問","可能形","受身形","使役形","自動詞・他動詞","条件表現","敬語の基礎","会話と読解","総復習"];
const n3=["N3 文法基礎","助詞の使い分け","複文と接続","条件・逆接","推量・判断","受身・使役の応用","敬語と場面表現","文章語彙","読解①","読解②","聴解①","聴解②","漢字語彙","副詞・接続詞","慣用表現","文法総合①","文法総合②","読解総合","聴解総合","模擬テスト"];
const data={N5:n5,N4:n4,N3:n3};
const sample={
N5:[{jp:'おはようございます。',r:'おはようございます',my:'မင်္ဂလာနံနက်ခင်းပါ။'},{jp:'わたしは ミンです。',r:'わたしは みんです',my:'ကျွန်တော်/ကျွန်မက မင်း ဖြစ်ပါတယ်။'},{jp:'これは なんですか。',r:'これは なんですか',my:'ဒါက ဘာလဲ။'}],
N4:[{jp:'あした いけたら、いきます。',r:'あした いけたら、いきます',my:'မနက်ဖြန် သွားနိုင်ရင် သွားမယ်။'},{jp:'べんきょうした ほうが いいです。',r:'べんきょうした ほうが いいです',my:'စာလေ့လာတာ ပိုကောင်းတယ်။'}],
N3:[{jp:'しっかり じゅんびして おきます。',r:'しっかり じゅんびして おきます',my:'သေချာပြင်ဆင်ထားမယ်။'},{jp:'この けいけんを いかしたいです。',r:'この けいけんを いかしたいです',my:'ဒီအတွေ့အကြုံကို အသုံးချချင်တယ်။'}]};
function home(){back.classList.add('hidden');app.innerHTML=`<section class="hero"><h1>ဂျပန်စာကို အစဉ်လိုက်လေ့လာမယ် 🇯🇵</h1><p>N5 → N4 → N3 • Kotoba • Grammar • Quiz • Progress</p></section><div class="grid">${['N5','N4','N3'].map(l=>`<div class="card" onclick="level('${l}')"><div class="level">${l}</div><div class="small">${data[l].length} Lessons</div><div class="progress"><div class="bar" style="width:${pct(l)}%"></div></div><div class="small">${pct(l)}% ပြီး</div></div>`).join('')}</div><div class="section">📝 Past Exam</div><div class="item"><b>2007–2026 JLPT မေးခွန်းဟောင်း</b><p class="my">မင်းပိုင်တဲ့ PDF/မေးခွန်းဖိုင်တွေကို ထည့်သွင်းဖတ်နိုင်အောင် Past Exam module ထည့်ထားမယ်။ မူပိုင်ခွင့်ရှိတဲ့ မေးခွန်းစာသားတွေကို app ထဲ တိုက်ရိုက်မကူးထည့်ထားပါ။</p><button class="primary" onclick="past()">Past Exam သို့</button></div>`}
function pct(l){return Math.round(data[l].filter((_,i)=>state.done[l+'-'+i]).length/data[l].length*100)}
function level(l){back.classList.remove('hidden');back.onclick=home;app.innerHTML=`<div class="section">${l} သင်ခန်းစာ</div>${data[l].map((x,i)=>`<div class="lesson" onclick="lesson('${l}',${i})"><div><h3>အခန်း ${i+1}</h3><div>${x}</div></div><span class="badge">${state.done[l+'-'+i]?'✓ ပြီး':'စလေ့လာ'}</span></div>`).join('')}`}
function lesson(l,i){back.onclick=()=>level(l);back.classList.remove('hidden');const items=sample[l];app.innerHTML=`<div class="section">${l} • အခန်း ${i+1}</div><div class="item"><h2>${data[l][i]}</h2><div class="tabs"><button class="active">Kotoba</button><button>Grammar</button><button>Quiz</button></div></div>${items.map(x=>`<div class="item"><div class="jp">${x.jp}</div><div class="reading">${x.r}</div><div class="my">${x.my}</div></div>`).join('')}<div class="note">💡 ဒီ lesson တွေကို နောက်ပိုင်းမှာ သင်ရိုးအလိုက် Kotoba၊ Grammar၊ ဥပမာဝါကျ၊ Quiz အပြည့်အစုံထပ်ဖြည့်နိုင်ပါတယ်။</div><button class="primary" onclick="complete('${l}',${i})">✓ ဒီအခန်းပြီးပြီလို့ မှတ်မယ်</button>`}
function complete(l,i){state.done[l+'-'+i]=true;save();level(l)}
function quiz(){back.classList.add('hidden');const q=[['これは ___ です。','なん','どこ','だれ',0],['わたしは がくせい ___。','です','ます','でした',0],['あした いけたら、___。','いきます','いきませんか','いきました',0]];let n=0;function render(){if(n>=q.length){app.innerHTML=`<div class="hero"><h1>Quiz ပြီးပါပြီ 🎉</h1><p>${q.length} ခုပြီး — မှန်တာ ${state.quiz||0} ခု</p></div><button class="primary" onclick="quiz()">ပြန်ဖြေမယ်</button>`;return}let x=q[n];app.innerHTML=`<div class="section">Mini Quiz ${n+1}/${q.length}</div><div class="item"><h2>${x[0]}</h2>${x.slice(1,4).map((a,i)=>`<button class="choice" onclick="ans(${i},${x[4]})">${a}</button>`).join('')}</div>`}window.ans=(i,c)=>{if(i===c){state.quiz=(state.quiz||0)+1;state.correct=(state.correct||0)+1;save()}n++;render()};render()}
function progress(){back.classList.add('hidden');app.innerHTML=`<div class="section">📈 မင်းရဲ့တိုးတက်မှု</div>${['N5','N4','N3'].map(l=>`<div class="item"><div class="stat"><b>${l}</b><b>${pct(l)}%</b></div><div class="progress"><div class="bar" style="width:${pct(l)}%"></div></div></div>`).join('')}<div class="item"><div class="stat"><span>Quiz ဖြေပြီး</span><b>${state.quiz||0}</b></div><div class="stat"><span>မှန်ကန်မှု</span><b>${state.correct||0}</b></div></div>`}
function past(){back.classList.remove('hidden');back.onclick=home;app.innerHTML=`<div class="section">📝 Past Exam</div><div class="item"><h2>2007–2026 July</h2><p class="my">JLPT မေးခွန်းဟောင်းတွေကို မင်းမှာရှိတဲ့ PDF/ပုံ/စာရွက်ဖိုင်တွေကနေ app အတွက် data အဖြစ် ပြောင်းထည့်နိုင်မယ့်နေရာပါ။</p><div class="note">မူပိုင်ခွင့်ရှိတဲ့ official exam questions ကို မူရင်းအတိုင်း ပြန်ထုတ်ပေးမယ့်အစား၊ မင်းတင်ပေးတဲ့ ကိုယ်ပိုင်/ခွင့်ပြုထားတဲ့ဖိုင်တွေကိုသာ အသုံးပြုနိုင်ပါတယ်။</div></div>`}
function route(t){if(t==='homeTab')home();if(t==='levels')level('N5');if(t==='quiz')quiz();if(t==='progress')progress()}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>route(b.dataset.tab));document.getElementById('home').onclick=home;home();
